### PR TITLE
int for tokens instead of wei; deploy contracts to sepolia

### PR DESCRIPTION
**Pull request by hollygrimm**
### 2a. Go code from:
```golang
collateral := big.NewInt(0)
```
to:
```golang
collateral := EtherToWei(0)
```

### 2b. Hardhat tests from:
```typescript
ethers.getBigInt(1),
```
to
```typescript
ethers.parseEther("1"),
```

## 3. Added fields to `.env` file to support other chains:
```bash
export INFURA_KEY=
export LOG_LEVEL=info
export NETWORK=geth
export WEB3_RPC_URL=ws://localhost:8546
export WEB3_CHAIN_ID=1337
```

### CODE REVIEW

**Comment by lukemarsden** [comment]
This looks great thank you! Please resolve the conflicts and again, confirm with a manual test that devstack is still working.

Will this require any changes to environment for the testnet? I e any deploy time considerations?

**Comment by hollygrimm** [comment]
@lukemarsden I resolved the conflicts and retested the devstack.
This should create no issues for the testnet.

**Review by lukemarsden — APPROVED** [review]

**Comment by lukemarsden** [comment]
great, approved! please merge :)

**Comment by lukemarsden** [comment]
and thank you!

**Pull request merged**
