### PR TITLE
change module version to v2

### PR DESCRIPTION
**Pull request by richardbremner**
### Review Type Requested (choose one):
- [ x ] **Glance** - superficial check (from domain experts)
- [ ] **Logic** - thorough check (from everybody doing review)

### Summary
Upping the version to v2 and we'll use manual tagging to identify releases (for now)

### Task/Issue reference

[Closes: add_link_here](https://github.com/Lilypad-Tech/lilypad/issues/79)

### Details (optional)
We will leave the current circleci short sha tag versioning in place for now.

When we release we'll just create a tag with the next version number, ie.

git tag v2.0.x
git push origin v2.0.x

go install github.com/Lilypad-Tech/lilypad@latest will automatically pull down the highest semantic version

### CODE REVIEW

**Comment by richardbremner** [comment]
fixing up a whole bunch of "/v2" needing added through the codebase

**Review by AquiGorka — APPROVED** [review]
@richardbremner approving to unblock, but I am not sure moving all the packages inside a `v2` namespace is the best thing to do, does it bring any benefit that we could put in place without such a big move?

**Comment by AquiGorka** [comment]
@richardbremner is this PR still relevant?

**Comment by richardbremner** [comment]
@AquiGorka i think it's still relevant, because it fixes the go install, which is otherwise still broken

**Comment by AquiGorka** [comment]
If that's the case, then we should rebase, resolve the conflicts and merge.

**Comment by AquiGorka** [comment]
@richardbremner let's figure out what we need to do here, the expectation is that after a fix is put in place we can do `go get github.com/Lilypad-Tech/lilypad/pkg/something/something` in a go codebase to install the required package (like, let's say, the [go bindings for the web3 contracts](https://github.com/Lilypad-Tech/lilypad/tree/main/pkg/web3/bindings) in the cron server, instead of copy pasting the abi and/or the binding file for pow)

**Comment by richardbremner** [comment]
i think this is out of date and we can track those other things separately. at the time i think we still had `go install` in the docs and that wasn't working

**Pull request closed without merging**
