### PR TITLE
feat: Changed rpc to Quicknode 

### PR DESCRIPTION
**Pull request by kelindi**
### Summary

This pull request makes the following changes:

- [ ] Updates the testnet.toml to use a new rpc endpoint
- [ ] Adds a test file to test basic rpc functions

### Test plan

Run the sdk_test.go, comment any additional rpc tests you think could be useful

### CODE REVIEW

**Comment by kquirapas** [comment]
Team @dev-ronelcanaria @DyepLucban @apquinit 

Here's a suggested **Test Plan**

# Objective

We must test the new QuickNode RPC in the context of the prod network so we must check if the new RPC works with the services that use the RPC

# Test Plan
1. Pull the entire network locally
2. Switch to `rpc_update` branch ([THIS](https://github.com/Lilypad-Tech/lilypad/tree/rpc_update))
3. As a sanity check, we can see if `sdk_test.go` by Ayush works
4. Build the tool and run jobs at least 10 times see if it works with the new RPC

**Comment by kquirapas** [comment]
Initial test by building the lilypad tool with the QuickNode RPC -> Got my angry cow

image

Next is testing @kelindi 's headless Web3SDK and see if it works on my end

**Comment by kquirapas** [comment]
@kelindi Your headless `sdk_test.go` doesn't do anything yet.. nothing to run?

**Comment by kquirapas** [comment]
> Team @dev-ronelcanaria @DyepLucban @apquinit
> 
> Here's a suggested **Test Plan**
> # Objective
> 
> We must test the new QuickNode RPC in the context of the prod network so we must check if the new RPC works with the services that use the RPC
> # Test Plan
> 
>     1. Pull the entire network locally
> 
>     2. Switch to `rpc_update` branch ([THIS](https://github.com/Lilypad-Tech/lilypad/tree/rpc_update))
> 
>     3. As a sanity check, we can see if `sdk_test.go` by Ayush works
> 
>     4. Build the tool and run jobs at least 10 times see if it works with the new RPC

GM team I have tested with this test plan (except @kelindi 's headless because there's nothing to run there yet)

The cows are cow-ing and moo-ing, hence I believe this should be seamless unless there's an edge case QuickNode is not supporting specifically which I'm already clarifying (See image below)

Screenshot 2024-09-11 at 2 25 30 PM

**Comment by apquinit** [comment]
image

Ran tests 10 times. No errors encountered, but no STDOUT as well.

**Comment by DyepLucban** [comment]
image
image

same with @apquinit , ran it 10times, no STDOUT as well

**Comment by kelindi** [comment]
> @kelindi Your headless `sdk_test.go` doesn't do anything yet.. nothing to run?

How are you running it? I'm currently able to run the two functions

**Review by alvin-reyes — APPROVED** [review]
LGTM.

**Pull request merged**
