### PR TITLE
README module edits, added lilysay

### PR DESCRIPTION
**Pull request by developersteve**

### CODE REVIEW

**Review by Zorlin — APPROVED** [review]

**Review by Zorlin — CHANGES_REQUESTED** [review]
Please change this to use **sdxl-pipeline**, the old sdxl module is unsupported and broken

**Comment by developersteve** [comment]
> Please change this to use **sdxl-pipeline**, the old sdxl module is unsupported and broken

Good catch, we probably need to look at depreciating/archiving and leaving notes on all the unsupported modules.

**Comment by Zorlin** [comment]
> > Please change this to use **sdxl-pipeline**, the old sdxl module is unsupported and broken
> 
> Good catch, we probably need to look at depreciating/archiving and leaving notes on all the unsupported modules.

Deprecating (depreciating is an entirely different thing!), but yes! Definitely

**Review by Zorlin — APPROVED** [review]
LGTM

**Pull request merged**
