### PR TITLE
chore: Add PR labeling again

### PR DESCRIPTION
**Pull request by rhochmayr**
### Review Type Requested (choose one):
- [x] **Glance** - superficial check (from domain experts)
- [ ] **Logic** - thorough check (from everybody doing review)

### Summary
This pull request brings back automated PR labeling by the Validate PR Conventional Commit (PRCC) action. PRCC v1.2.0 seems to keep existing labels when using `custom_labels`.

### Task/Issue reference

Closes: (https://github.com/Lilypad-Tech/lilypad/issues/245)

### CODE REVIEW

**Comment by bgins** [comment]
Thanks for the PR! 🙏  

The action run is failing with a `Error: Resource not accessible by integration`. Likely something with permissions around running actions from a fork. Will look into it.

**Comment by bgins** [comment]
Alright, I have a theory about how we can get the action to run. According to this announcement: https://github.blog/news-insights/product-news/github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks, we may be able to trigger the action against the base instead of the fork by changing the event from `pull_request` to `pull_request_target`.

Could you update the `on` event here to `pull_request_target`?

https://github.com/Lilypad-Tech/lilypad/blob/af992f89723c92f295d19485e9d49a5d3629d509/.github/workflows/validate_pr_title.yml#L4

Hopefully that will let us run the action.

Thanks for helping us work through this! We're going to need our actions running for open source contributors going forward, and the help sorting out the details is much appreciated.

**Comment by bgins** [comment]
Thanks for pushing the `pull_request_target` change. Seems that wasn't what we need. I'll keep investigating.

**Comment by rhochmayr** [comment]
I can reproduce the same issue with another fork of the pr-labeling repo I used to test this out initially. Will also have a look if I can find anything.

**Comment by rhochmayr** [comment]
I got this to work by bringing the change to `pull_request_target` into the main branch of the base repository first. After synching that change into the forked repository it started to work. Otherwise it kept using the old workflow version for the PR. I guess this could be introduced from internal contributors first.

**Comment by bgins** [comment]
> I got this to work by bringing the change to `pull_request_target` into the main branch of the base repository first. After synching that change into the forked repository it started to work. Otherwise it kept using the old workflow version for the PR. I guess this could be introduced from internal contributors first.

Thanks for investigating! And yep, that makes sense. I will put a PR in to change over to `pull_request_target` and get someone on the team to review. Then we can get the actions running here. 🙂

**Comment by bgins** [comment]
Alright, we've merged the `pull_request_target` change: https://github.com/Lilypad-Tech/lilypad/pull/264. Hopefully if we bring that in from `main`, that will get the action running here.

**Comment by rhochmayr** [comment]
Should it have both triggers or just `pull_request_target`? It ended up with a duplicate in my fork because i changed `pull_request` to `pull_request_target` already. So i removed on of them just before. 

Now I'm wondering if you wanted both, `pull_request` as well as `pull_request_target` in there?

**Comment by bgins** [comment]
> Should it have both triggers or just `pull_request_target`? It ended up with a duplicate in my fork because i changed `pull_request` to `pull_request_target` already. So i removed on of them just before.
> 
> Now I'm wondering if you wanted both, `pull_request` as well as `pull_request_target` in there?

Ah apologies for not explaining! The action was not running when I made the change only use `pull_request_target`, but this may be similar to what we have encountered here where we needed the change on `main` first. I suspected we might need both, but looking at a PR from earlier today (https://github.com/Lilypad-Tech/lilypad/pull/265), the action ran twice:

CleanShot 2024-07-29 at 16 23 05@2x

And the action has run here on `pull_request_target`, so looks like we are good to go! Will do one last check in a repo matching all of our repo settings here, then we can get this merged. Thanks for all your patience working through this with us!

**Review by bgins — APPROVED** [review]
Alright! Last check completed, everything is good to go. Merging this shortly, followed by `fix` PR to test it in concert with the release pipeline.

Huge thanks again for the contribution and for working through the fine details of accepting open source contributions with us. Your contribution will be remembered. ❤️

**Comment by bgins** [comment]
It looks like there is something we are missing that is specific to our repository setup that continues to cause issues where existing labels are removed. 

We tested the labeling change over in #265, by adding a `documentation` label and changing the PR title. Unfortunately, the `documentation` label was removed when adding the PR title associated label:

CleanShot 2024-07-30 at 09 48 00@2x

We'll have someone on the Lilypad team look through our settings to see what we can find.

**Comment by rhochmayr** [comment]
I think this was still using the old workflow file before you made the merge of the PR that brings the labelling back.
https://github.com/Lilypad-Tech/lilypad/actions/runs/10166211780/workflow

**Comment by bgins** [comment]
Ah yes, that does seem to be the case. Will bring the change back and properly test it.

Apologies for the extreme caution bringing this change in. We have had some issues where our release pipeline get into an infinite loop creating releases when labels are removed, so we are being a bit guarded about it.

And again, thanks for your help debugging. ❤️

**Comment by rhochmayr** [comment]
Ah, not sure if that has anything to do with it, but maybe this behaves slightly differently for existing / open PRs that haven't synchronized yet? Sorry for all the back and forth. I think I will leave it to the Pro's from here 😃 

And thanks for all the patience so far!

**Comment by rhochmayr** [comment]
Sorry for the interruption again. So I think what happens is, it removes labels if they are in the list of `custom_labels` and don't relate to the PR title. Labels that are not included in the list are kept.

image

Here it will keep those (`fix` is based on the PR title, `bug` and `enhancement` are not in the list of `custom_labels`, they are kept too. When I additionally added `chore` or `documentation` - those got removed. Assuming because they are in the list of `custom_labels` and don't fit the PR title.

**Comment by bgins** [comment]
> Sorry for the interruption again. 

Totally alright! Appreciate the conversation.

> So I think what happens is, it removes labels if they are in the list of `custom_labels` and don't relate to the PR title. Labels that are not included in the list are kept.

> Here it will keep those (fix is based on the PR title, bug and enhancement are not in the list of custom_labels, they are kept too. When I additionally added chore or documentation - those got removed. Assuming because they are in the list of custom_labels and don't fit the PR title.

Yes, I think this is exactly what happened. The `documentation` label was removed because it's part of the custom labels.

We did a second test with a test on a PR with a `help wanted` label and the label was preserved: https://github.com/Lilypad-Tech/lilypad/pull/270

In addition, we merged that PR to test the release pipeline and the `release-please` merge PR labels are preserved: https://github.com/Lilypad-Tech/lilypad/pull/271

So yeah, everything is good and works well with our release pipeline. Once again, thanks for the contribution and your help bringing it in. Much appreciated! 🙌

**Pull request merged**
