### PR TITLE
chore: sign cla + fix typos

### PR DESCRIPTION
**Pull request by omahs**
chore: sign cla + fix typos

### CODE REVIEW

**Comment by bgins** [comment]
Hey @omahs! Thanks for all the typo fixes, much appreciated! ❤️ 

One last step for signing the CLA. Could you add an entry with your name and GitHub username to the `NOTICES.md`? (https://github.com/Lilypad-Tech/lilypad/blob/main/NOTICES.md)

**Comment by omahs** [comment]
@bgins Thanks for the quick review! Just added the change to `NOTICES.md`

**Comment by bgins** [comment]
> @bgins Thanks for the quick review! Just added the change to `NOTICES.md`

Thanks @omahs! The field for "Licensee’s name" should be your real name because this is a legal document. 

If you feel uncomfortable providing your real name in public, we could consider an alternative like signing a PDF version of the CLA. If that's the case, ping me in the `#open-source` channel in Discord (my Discord handle is also `@bgins`) and we can start a DM to work it out.

**Comment by omahs** [comment]
@bgins I'm completely fine with someone from your team redoing the commits instead, as I’d prefer to remain pseudonymous. I hope that's okay with you.

**Comment by bgins** [comment]
> @bgins I'm completely fine with someone from your team redoing the commits instead, as I’d prefer to remain pseudonymous. I hope that's okay with you.

Yes, that's totally alright! Completely understand your desire to remain pseudonymous.

I will put in a PR with the typo fixes, and thank you for bringing the issues to our attention.

**Comment by bgins** [comment]
Closed in favor of #448

**Pull request closed without merging**
